OSC/osc-ood-config

apps.awesim.org/apps/bc_desktop/owens.yml, apps.awesim.org/apps/bc_desktop/vdi-owens.yml, ondemand.osc.edu/apps/bc_desktop/owens.yml, ondemand.osc.edu/apps/bc_desktop/vdi-owens.yml, ood.osc.edu/apps/bc_desktop/owens.yml, ood.osc.edu/apps/bc_desktop/vdi-owens.yml
Requires `bc_desktop` >0.1.2. Allows user to choose between Mate or Xfce desktop for Owens, with Xfce being default.
=> Add Xfce to Owens

apps.awesim.org/apps/bc_desktop/pitzer.yml, apps.awesim.org/apps/bc_desktop/vdi-pitzer.yml, apps.awesim.org/apps/bc_desktop/vdi-ruby.yml, ondemand.osc.edu/apps/bc_desktop/pitzer.yml, ondemand.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ondemand.osc.edu/apps/bc_desktop/vdi-ruby.yml, ood.osc.edu/apps/bc_desktop/pitzer.yml, ood.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ood.osc.edu/apps/bc_desktop/vdi-ruby.yml
This pull request adds pitzer.yml and vdi-pitzer.yml. 
It works fine but still needs more information about Pitzer node type. The current node_type information is from Ruby cluster. 
```
node_type:
widget: select
label: "Node type"
help: |
- **any** - (*12 cores*) Chooses anyone of the available Pitzer nodes.
This reduces the wait time as you have no requirements.
- **vis** - (*12 cores*) This node includes an NVIDIA Tesla M2070 GPU
with an X server running in the background. This allows for Hardware
Rendering with the GPU typically needed for 3D visualization using
VirtualGL. There are currently only 128 of these nodes on Pitzer.
- **gpu** -  (*12 cores*) This node includes an NVIDIA Tesla M2070 GPU
allowing for CUDA computations. There are currently only 128 of these
nodes on Pitzer. …
```
=> add Pitzer desktop config

stat.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
Same as the update made to the [regular owens rstudio_server](https://github.com/OSC/bc_osc_rstudio_server/pull/26). Users cannot save and create PDF markdown files without this module.
=> add texlive module to bc_osc_rstudio_server

stat.osc.edu/apps/bc_osc_rstudio_server/form.js, stat.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
In draft at the moment because we're working with sci-apps to get it right before deploying.
But this updates the stats deployment with new classes/workshops available and these new classes use new modules.
=> update rstudio stat form to include new classes and modules

stat.osc.edu/apps/bc_osc_rstudio_server/form.js, stat.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
This adds the OSC Workshop as a module for stats.osc.edu also adds a default version (the old module version string) in case someone logs in and they're not a part of any class.
=> make a default version of no classes and add the OSC Workshop class

stat.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
OK sorry for the noise.  The hidden staff toggle isn't working right because I was setting `value` instead of `checked_value`.
=> stats form needs checked_value not value

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/locales/en.yml, test/apps/shell_test.rb
More classroom updates. In draft at the moment as I need bc_osc_jupyter 0.14.1 (just released) before jupyterlab will work correctly in for classrooms.
- add the OSCJUPYTER module for staff to test against
- allow jupyter users to choose jupyterlab
- update the stat2480 textbook link
=> More class updates

apps.awesim.org/apps/bc_desktop/pitzer-exp.yml, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer-exp.yml, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb, ood.osc.edu/apps/bc_desktop/pitzer-exp.yml, ood.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
- use the --exclusive flag to get the whole node
- there's no real need to request 1 or 3 GPUs. If one launches
a job with 48 cores and 1 GPU, the remaining GPU on that node
is inaccessible so we may as well just allocate and use it.
=> Add Pitzer-Expansion desktop

class.osc.edu/locales/en.yml
add ANTHROP 9982 to useful links and change headings for accessability.
This does add an `h1` which is kind of unnecessary for visual folks but would be needed for screen readers. I'm open to hiding it in css instead.
=> add ANTHROP 9982 to useful links and change headings for accessability

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb, ood.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
if before_script string content is specified, this will be placed into
the job script instead of before.sh being sourced
since bc_desktop only exports the module function we just repeat that
and then set XDG_RUNTIME_DIR to $TMPDIR
XDG_RUNTIME_DIR is supposed to be 700, owned by the user, exist only for
the duration of the app run, and then be deleted; using $TMPDIR of the
batch job ensures all these occur
=> set XDG_RUNTIME_DIR using before_script

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb, ood.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
apparently relative paths for XDG_RUNTIME_DIR create something in $TMPDIR, but actually use $HOME. So this was created $HOME/xdg files.
=> fix XDG_RUNTIME_DIR

apps.awesim.org/apps/myjobs/templates/Simple_OMP_Job_Slurm/manifest.yml, apps.awesim.org/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.c, apps.awesim.org/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.sh, ondemand.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/manifest.yml, ondemand.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.c, ondemand.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.sh, ood-test.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/manifest.yml, ood-test.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.c, ood-test.osc.edu/apps/myjobs/templates/Simple_OMP_Job_Slurm/omp-hello.sh
Job output:
```
Hello World from thread number 16
Hello World from thread number 46
Hello World from thread number 15
Hello World from thread number 12
Hello World from thread number 19
Hello World from thread number 28
Hello World from thread number 17
Hello World from thread number 1
Hello World from thread number 24
Hello World from thread number 14
Hello World from thread number 32
Hello World from thread number 0
Hello World from thread number 40
Number of threads is 48
Hello World from thread number 20
Hello World from thread number 23
Hello World from thread number 33
Hello World from thread number 29
Hello World from thread number 8
Hello World from thread number 35
Hello World from thread number 30
Hello World from thread number 34
Hello World from thread number 22
Hello World …
```
=> Fix Hello OpenMP World in C for Slurm

apps.awesim.org/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/manifest.yml, apps.awesim.org/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/slurm_script.sh, ondemand.osc.edu/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/manifest.yml, ondemand.osc.edu/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/slurm_script.sh, ood-test.osc.edu/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/manifest.yml, ood-test.osc.edu/apps/myjobs/templates/Basic_LAMMPS_Parallel_Job_Pitzer-Exp/slurm_script.sh
**Job Output:**
```
LAMMPS (3 Mar 2020)
using 48 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.11428 1.92998 1.11428
Created orthogonal box = (0 0 -0.278569) to (111.428 77.1994 0.278569)
2 by 1 by 1 MPI processor grid
Created 8141 atoms
create_atoms CPU = 0.00529075 secs
...
Step Temp E_pair E_mol TotEng Press Volume 
0  0.065993465   -3.2595015            0   -3.1984123 -0.035939913    8605.5917 
200  0.060035253   -3.2531886            0   -3.1976149  -0.22757684    8638.5331 
400   0.06054278   -3.2510706            0   -3.1950271  -0.42811733    8677.8288 
600  0.060576995    -3.246816            0   -3.1907408  -0.60017647    8717.6131 
800  0.060802753   -3.2413477            0   -3.1850635  -0.74499308    8756.4512 
1000  0.061812114   -3.2349942            0 …
```
=> Fix LAMMPS for Slurm

apps.awesim.org/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb, ondemand.osc.edu/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb
Brand new users can't create myjobs databases because we hit this initializer and there's no workflow table yet.
So this adds a guard clause.
=> only update myjobs DB records if the database exists

apps.awesim.org/apps/activejobs/initializers/filter.rb, ondemand.osc.edu/apps/activejobs/initializers/filter.rb
This PR fixes the Active Jobs filter to show jobs that are submitted to the Pitzer cluster. 
Jobs submitted with the Linux Host Adapter aren't shown still, see bug report here: https://github.com/OSC/ondemand/issues/693
=> Fix Active Jobs filter for Pitzer jobs

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_jupyter/submit.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/submit.yml.erb
Users with no classroom projects will now be able to view a project select menu. This will start a jupyter & rstudio app similar to the regular ondemand with no class modules loaded.
=> show project field if no classrooms are available.

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_jupyter/submit.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/submit.yml.erb
class apps should use account instead of 'project' to align with their actual versions. Otherwise I get errors about `undefined local variable or method 'account'`.
=> class apps should use account instead of 'project' 

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.js
First there's a small bug introduced in #150 where I should have called `change_account` instead of `show_account`.
Secondly, I think the initialization doesn't quite work with using `.val()` on a select widget (it kept using my cached value, not the classroom project it should have), so this forces the change by calling `change()` on it.
=> Fix classes

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
Vis and GPU desktops currently cannot request any more than 1 core (the default). This fixes that.
=> vis and gpu desktops should respect the core counts

.github/workflows/test.yml, Gemfile.lock
upgrade dependencies to current bundler 2 and ruby 2.7+ because we need to be able to locally run rake test which we can't at the moment.
=> upgrade dependencies to current bundler 2 and ruby 2.7+

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
desktops can now correctly use srun & sbatch by setting exports to all.
Previously folks would have to run `srun --export=ALL ...` to get Slurm to recognize the PATH or other environment variables. This also fixes a bug where desktops in parallel queues have all the cores on the machine but srun does not recognize this fact.
=> desktops can now correctly use srun & sbatch by setting exports to all

hooks/k8s-bootstrap.sh
This is needed if anyone at OSC wants to test using the private docker registry `ondemand` project namespace.  This will not be needed if https://github.com/OSC/ondemand/pull/995 is merged first.
=> Bootstrap private registry secret

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
Reverts OSC/osc-ood-config#174 because classroom's already have this module.
=> Revert "add texlive to jupyter classes"

class.osc.edu/apps/bc_osc_rstudio_server/form.js
allow RNA SEQ workshop to choose cores, though putting this on HOLD just because we may not use it. But it's here in case we do.
=> [HOLD] allow RNA SEQ workshop to choose cores

apps.awesim.org/apps/dashboard/initializers/ood.rb, class.osc.edu/apps/dashboard/initializers/stats2480.rb, ondemand.osc.edu/apps/dashboard/initializers/ood.rb
add a force option for gpfs outages. This is so that we can drop a file here and we won't add those paths even if the Prometheus alert hasn't fired yet.
=> add a force option for gpfs outages

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.js
The Kubernetes logic was copied from RStudio app
Move GRADTDA5620 to Kubernetes
Because GRADTDA5620 was going to K8 for RStudio, made same change for Jupyter, but can remove if needed.
=> Kubernetes classroom support for Jupyter

class.osc.edu/apps/bc_osc_rstudio_server/form.js
Per Summer this class is going to run for 3 hours so giving them up to 4 hours to use K8 pod.
=> Increase max walltime for BMI8130_OSU

class.osc.edu/apps/bc_osc_rstudio_server/form.js
init cores to 1 bc most classes can't change it. If you were in the class with 4 and another class - switching back and forth you'd end up starting the second class with 4 cores when you should only have used 1.
=> init cores to 1 bc most classes can't change it

ondemand.osc.edu/apps/dashboard/env
ondemand to use the logo in navbar. Login to class.osc.edu (or dev/test) to see the affect as it's already got this configuration.
=> ondemand to use the logo in navbar

ondemand.osc.edu/apps/dashboard/env
Reverts OSC/osc-ood-config#218.  Images are not accessible in 2.0.
=> Revert "ondemand to use the logo in navbar"

ondemand.osc.edu/apps/dashboard/initializers/ood.rb
@johrstrom This will have to be rolled out to test sometime next week and then likely save for production until June downtime.  If that large gap between test and production will cause issues, we can just delay test rollout till week before downtime.
=> Fix Keycloak URL to work with Keycloak 18

class.osc.edu/apps/dashboard/initializers/k8s_core.rb, ondemand.osc.edu/apps/dashboard/initializers/k8s_core.rb
These initializers are actually broken.
=> require ood_core for these

apps.awesim.org/apps/bc_desktop/owens.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb
the gpu stuff for ascend broke the other desktops. so this adds an empty gpu field for them.
=> specify gpus on owens & pitzer

apps.awesim.org/apps/dashboard/env, apps.totalsim.us/apps/dashboard/env, ondemand.osc.edu/apps/dashboard/env
enable module directories on all portals. This will enable us to use the automatic modules (`auto_modules_<module>`) as described in the documentation below.
https://osc.github.io/ood-documentation/latest/how-tos/app-development/interactive/form.html#auto-bc-form-options
=> enable module directories on all portals

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
allow cpus to pass through to the CLI so that ascend desktops can request N CPUs when requesting M nodes.
=> allow cpus to pass through to the CLI

apps.awesim.org/apps/bc_desktop/ascend.yml.erb, apps.awesim.org/apps/bc_desktop/owens.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, apps.awesim.org/apps/bc_desktop/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/ascend.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/vdi.yml.erb
enable gnome desktops now that Gnome is fixed for 3.1.
=> enable gnome desktops

apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
Based on the idea that `any` node type + `1 gpu` should not override number of gpus on form submission.
=> Fixes bc_desktop behavior

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
There's a bug right now where we're always requesting GPUs after #254. This kinda reverts that back to what it was before then adds the ability to request `any` node type with `gpus` set to 1 or more and get a gpu node.
=> Gpu bug fix

apps.awesim.org/apps/bc_desktop/cardinal.yml.erb, apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, apps.awesim.org/apps/bc_desktop/vdi.yml, ondemand.osc.edu/apps/bc_desktop/cardinal.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/vdi.yml
add cardinal to lw desktops - and remove Gnome as an option
=> add cardinal to lw desktops - and remove Gnome as an option

apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb
force XDG_RUNTIME_DIR to be a new tmp directory because /tmp/xdg_runtime is hard coded and isn't a temporary file system local to the container.
=> force XDG_RUNTIME_DIR to be a new tmp directory

apps.awesim.org/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb, apps.awesim.org/apps/myjobs/initializers/workflow_presubmit_validation.rb
=> fix awsim myjobs initializers
