OSC/osc-ood-config

apps.awesim.org/apps/bc_desktop/oakley.yml, apps.awesim.org/apps/bc_desktop/vdi-oakley.yml, ondemand.osc.edu/apps/bc_desktop/oakley.yml, ondemand.osc.edu/apps/bc_desktop/vdi-oakley.yml, ood.osc.edu/apps/bc_desktop/oakley.yml, ood.osc.edu/apps/bc_desktop/vdi-oakley.yml
=> Add expires warning for Oakley Desktop and VDI

apps.awesim.org/apps/myjobs/templates/default/sequential_job.sh, ondemand.osc.edu/apps/myjobs/templates/default/sequential_job.sh, ood-test.osc.edu/apps/myjobs/templates/default/sequential_job.sh
fix https://github.com/OSC/ood-myjobs/issues/289
=> file permission issue

.gitignore, apps.awesim.org/apps/bc_desktop/owens.yml, apps.awesim.org/apps/bc_desktop/pitzer.yml, apps.awesim.org/apps/bc_desktop/ruby.yml, apps.awesim.org/apps/bc_desktop/vdi-owens.yml, apps.awesim.org/apps/bc_desktop/vdi-pitzer.yml, apps.awesim.org/apps/bc_desktop/vdi-ruby.yml, ondemand.osc.edu/apps/bc_desktop/owens.yml, ondemand.osc.edu/apps/bc_desktop/pitzer.yml, ondemand.osc.edu/apps/bc_desktop/ruby.yml, ondemand.osc.edu/apps/bc_desktop/vdi-owens.yml, ondemand.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ondemand.osc.edu/apps/bc_desktop/vdi-ruby.yml, ood.osc.edu/apps/bc_desktop/owens.yml, ood.osc.edu/apps/bc_desktop/pitzer.yml, ood.osc.edu/apps/bc_desktop/ruby.yml, ood.osc.edu/apps/bc_desktop/vdi-owens.yml, ood.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ood.osc.edu/apps/bc_desktop/vdi-ruby.yml
This is WIP just to be sure this is the verbiage you're looking for, or if you wanted an actual like like an <a href=".."> type thing.
=> verbage changes for desktop apps

ondemand.osc.edu/apps/dashboard/env, ondemand.osc.edu/locales/en.yml
Requires https://github.com/OSC/ood-dashboard/pull/483
=> Enable balances for OSC OnDemand

ondemand.osc.edu/locales/en.yml
This removes the text "Consider requesting additional RUs".
=> Adjust balance message per OSCUS-780

Gemfile
Updating rake will get rid of our security alert.
=> update rake to be inline with other projects

apps.awesim.org/apps/dashboard/env, ondemand.osc.edu/apps/dashboard/env, stat.osc.edu/apps/dashboard/env
Fix the OSC support url because what's there now is broken.
=> fix the OSC support url

apps.awesim.org/apps/bc_desktop/vdi-owens.yml, apps.awesim.org/apps/bc_desktop/vdi-pitzer.yml, apps.awesim.org/apps/bc_desktop/vdi-ruby.yml, ondemand.osc.edu/apps/bc_desktop/vdi-owens.yml, ondemand.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ondemand.osc.edu/apps/bc_desktop/vdi-ruby.yml, ood.osc.edu/apps/bc_desktop/vdi-owens.yml, ood.osc.edu/apps/bc_desktop/vdi-pitzer.yml, ood.osc.edu/apps/bc_desktop/vdi-ruby.yml
Try to fix #49 by having simpler language around VDIs.
=> update vdi descriptions for #49

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_jupyter/submit.yml.erb
add jupyter configuration to class.osc.edu
=> add jupyter configuration to class.osc.edu

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/submit.yml.erb
Classroom updates for jupyter and rstudio.  Though this can't be pulled in and released until [this bc_osc_jupyter update](https://github.com/OSC/bc_osc_jupyter/pull/44) is merged and released.
=> Class updates

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_jupyter/submit.yml.erb, class.osc.edu/locales/en.yml
Add PHYSICS6820 to jupyter class
=> Add PHYSICS6820 to jupyter

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/locales/en.yml
There's a bug in the PHYSICS 6820 class.  Also we were requested to remove the website link for stat 2480.
=> Jupyter bugfix

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
add PUBHLTH 5015 class to rstudio
=> add PUBHLTH 5015 class to rstudio

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
add PHYS280_WIT to bc_osc_jupyter
=> add PHYS280_WIT to bc_osc_jupyter

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
add class/BANA7025 module to bc_rstudio_server
=> add class/BANA7025 module to bc_rstudio_server

class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
Quick fix for class.osc.edu. Surprisingly, this was the only thing that was required.
=> Class pitzer exp updates

class.osc.edu/apps/bc_osc_rstudio_server/form.js
a small update to allow OSCWORKSHOP to be able to choose cores
=> allow OSCWORKSHOP to be able to choose cores

apps.awesim.org/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/manifest.yml, apps.awesim.org/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/slurm_script.sh, ondemand.osc.edu/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/manifest.yml, ondemand.osc.edu/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/slurm_script.sh, ood-test.osc.edu/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/manifest.yml, ood-test.osc.edu/apps/myjobs/templates/Basic_Gaussian_Pitzer-Exp/slurm_script.sh
The script runs fine once I had group permission. The only issue I've found was with `g16 < glucose.com` which did not create a log file.
=> Fix Gaussian's Slurm job template

apps.awesim.org/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb, ondemand.osc.edu/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb
Custom initializer is idempotent - you can run it multiple times and it only takes affect the first time - since it will not find any records after it fixes them all.
=> Job Composer: update all records of pitzer-exp to pitzer

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
add PHYSICS 4032 OU to jupyter
=> add PHYSICS 4032 OU to jupyter

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> add codeclub to rstudio

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
fix pitzer desktop to cast bc_num_slots to integers and use the correct arguments to request hugemem.
=> fix pitzer desktop 

apps.awesim.org/apps/bc_desktop/owens-slurm.yml, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens-slurm.yml, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
add slurm-owens desktop and slightly modify slurm.yml.erb to support owens and pitzer
=> add slurm-owens desktop

apps.awesim.org/apps/bc_desktop/submit/vdi-submit.yml.erb, apps.awesim.org/apps/bc_desktop/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi-submit.yml.erb, ondemand.osc.edu/apps/bc_desktop/vdi.yml.erb
add owens-slurm quick option to VDIs
=> add owens-slurm quick option to VDIs

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> add SOCIO3549 class

apps.awesim.org/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb, ondemand.osc.edu/apps/myjobs/initializers/ood_appkit_pitzer_exp_fix.rb
job composer also change owens-slurm records to owens
=> job composer also change owens-slurm records to owens

hooks/k8s-bootstrap.sh, hooks/pre-hook.sh, hooks/set-k8s-creds.sh
Add full pre hook that calls k8s bootstrap and setting k8s credentials.
=> add full pre hook that calls k8s bootstrap and setting k8s credentials

apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb
VDIs also need to set XDG_RUNTIME_DIR to fix Mate desktops
=> VDIs also need to set XDG_RUNTIME_DIR to fix Mate desktops

.github/workflows/test.yml, .travis.yml
use github actions instead of travis-ci
=> use github actions instead of travis-ci

.github/workflows/test.yml, .gitignore, Gemfile.lock
Fixes #119 completely by adding shellcheck.
=> add shellcheck to gh actions

apps.awesim.org/apps/bc_desktop/owens.yml, apps.awesim.org/apps/bc_desktop/pitzer.yml, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml, ondemand.osc.edu/apps/bc_desktop/pitzer.yml, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
add an option for cores on the Desktop apps
=> add an option for cores on the Desktop apps

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
This adds a new jupyter class and changes the osc workshop to a different project id.
=> New modules

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> add BM7331 to class.osc.edu

class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> rm bad : in rstudio form

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> add GRADTDA 5402 to rstudio

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
update the project for TDAI to PAS1882
=> update the project for TDAI to PAS1882

apps.awesim.org/apps/bc_desktop/owens.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, apps.awesim.org/apps/bc_desktop/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/vdi.yml.erb
mv the bc_account field to a select widget with only valid groups as options
=> account select widget

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb
=> submits need to set accounting_ids

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
=> add demo project to rstudio

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
After talking with the PI the class is actually 5194.01 and so the module has been changed to `class/CSE 519401` for the same.
=> append 01 to CSE 5194

apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb
VDIs should also export=ALL so command like `sbatch` or `srun` work out of the box.
=> VDIs should also export=ALL

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
GRADTDA 5622 wants to default users to jupyterlab instead
=> GRADTDA 5622 wants to default users to jupyterlab instead

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
add add-PAS1952 to class osc edu
=> add add-PAS1952 to class osc edu

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
Update new modules paths for jupyter and rstudio classroom forms
=> Use new classroom mod

class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
add texlive to jupyter classes so folks can export notebooks as pdfs.
=> add texlive to jupyter classes

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb, class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
add 2021CCCBISR to jupyter and rstudio
=> add 2021CCCBISR to jupyter and rstudio

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
=> add MATH2530_OU class

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
=> add PHYS5071_OU to classrooms

class.osc.edu/apps/dashboard/views/widgets/_helpful_links.html.erb
add helpul links widget to classrooms
=> add helpul links widget to classrooms

class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
fix rstuido and k8s classes. If you're in more than 1 rstudio class - it hides all the other options (potentially the option you're looking for).
=> fix rstuido and k8s classes

class.osc.edu/apps/bc_osc_rstudio_server/form.js
migrate BMI5730 to kuberenetes
=> migrate BMI5730 to kuberenetes

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
add ASTRONOMY8824_OSU and support k8s w/ pitzer node types for jupyter apps.
=> add ASTRONOMY8824_OSU and support k8s w/ pitzer

class.osc.edu/apps/bc_osc_rstudio_server/form.js, class.osc.edu/apps/bc_osc_rstudio_server/form.yml.erb
update stat2480 and move it to k8s
=> update stat2480 and move it to k8s

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
add BMI5780_OSU to pitzer kubernetes
=> add BMI5780_OSU to pitzer kubernetes

class.osc.edu/apps/bc_osc_jupyter/form.js
give PHYSICS5680_OSU 4 cores and let them choose their core allocations.
=> give PHYSICS5680_OSU 4 cores

apps.totalsim.us/apps/dashboard/initializers/ood.rb
enable the files app in totalsim
=> enable the files app in totalsim

class.osc.edu/apps/bc_osc_jupyter/form.js, class.osc.edu/apps/bc_osc_jupyter/form.yml.erb
=> add tdai osu classroom

class.osc.edu/apps/bc_osc_jupyter/form.js
increaes TDAI's walltime to 5 hours.
=> increaes TDAI's walltime

ondemand.osc.edu/apps/dashboard/views/widgets/_classroom.html, ondemand.osc.edu/apps/dashboard/views/widgets/_jupyter_update.html
add widgets for jupyter updates and the link to class osc edu.
=> add widgets for updates

apps.awesim.org/apps/dashboard/env, ondemand.osc.edu/apps/dashboard/env
enable dynamic batch connect javascript in ondemand.
=> enable dynamic batch connect javascript

ondemand.osc.edu/apps/dashboard/views/widgets/_jupyter_update.html
add downtime date and fix version expression for the jupyter panel.
=> add downtime date and fix version expression

ondemand.osc.edu/apps/dashboard/views/widgets/_jupyter_update.html
update times on this panel to be in the past.
=> update times on this panel

class.osc.edu/apps/dashboard/initializers/k8s_core.rb, ondemand.osc.edu/apps/dashboard/initializers/k8s_core.rb, ondemand.osc.edu/apps/dashboard/views/widgets/_classroom.html
add monkey patch initializers for ood_core so that `bc_classroom_rstudio` can use R/4.1.0.
=> add monkey patch initializers for ood_core

class.osc.edu/apps/dashboard/initializers/k8s_core.rb, ondemand.osc.edu/apps/dashboard/initializers/k8s_core.rb
need to require specific stuff for this to work.
=> need to require specific stuff

apps.awesim.org/apps/bc_desktop/ascend.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, apps.awesim.org/apps/bc_desktop/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/ascend.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/vdi.yml.erb
add Ascend desktop and VDIs.  Note this also has some bug fixes like
* broken links
* cores should be a number_field
* renamed VDIs to Lightweight Desktop
=> add Ascend desktop and VDIs

apps.awesim.org/apps/bc_desktop/vdi.yml.erb, hooks/pre-hook.sh, ondemand.osc.edu/apps/bc_desktop/vdi.yml.erb
re-label ascend-login cluster to just be ascend.
=> re-label ascend-login cluster

apps.awesim.org/apps/bc_desktop/ascend.yml.erb, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/ascend.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
allow ascend to choose # of gpus
=> allow ascend to choose # of gpus

apps.awesim.org/apps/bc_desktop/ascend.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/ascend.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb
remove c18 options and set ascend desktop to default to 1 core.
=> remove c18 options

apps.awesim.org/apps/bc_desktop/owens.yml.erb, apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/owens.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
allow for partial access to huge & largemem nodes for the desktop apps.
=> allow for partial access to huge & largemem nodes

apps.awesim.org/apps/dashboard/env, apps.totalsim.us/apps/dashboard/env, ondemand.osc.edu/apps/dashboard/env
=> add facl domain for 2.1

apps.awesim.org/apps/shell/env, class.osc.edu/apps/shell/env, ondemand.osc.edu/apps/shell/env
allow shell access to ascend nodes and remove ruby.
=> allow ascend nodes and remove ruby

ondemand.osc.edu/apps/dashboard/views/widgets/_classroom.html
rm this inline style so that it fits within the container.
=> rm this inline style

apps.awesim.org/apps/bc_desktop/submit/slurm.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb
use `--nv` to correctly use gpus on ascend
=> use --nv to correctly use gpus on ascend

apps.awesim.org/apps/bc_desktop/pitzer.yml.erb, ondemand.osc.edu/apps/bc_desktop/pitzer.yml.erb
remove license field from pitzer because pitzer has no licensed software.
=> remove license field from pitzer

apps.awesim.org/apps/bc_desktop/cardinal.yml.erb, ondemand.osc.edu/apps/bc_desktop/cardinal.yml.erb
=> add vis nodes to cardinal

apps.awesim.org/apps/shell/env, ondemand.osc.edu/apps/shell/env
shell ping pong and set max duration to 2hrs
=> shell ping pong and set max duration to 2hrs

apps.awesim.org/apps/shell/env, ondemand.osc.edu/apps/shell/env
This was the wrong environment variable to set to a boolean.
=> fix shell ping pong

apps.awesim.org/apps/shell/env, ondemand.osc.edu/apps/shell/env
extend shell duration to 8 hrs
=> extend shell duration to 8 hrs

apps.awesim.org/apps/bc_desktop/cardinal.yml.erb, ondemand.osc.edu/apps/bc_desktop/cardinal.yml.erb
allow cardinal desktops to use licenses
=> allow cardinal desktops to use licenses

apps.awesim.org/apps/bc_desktop/submit/vdi.yml.erb, ondemand.osc.edu/apps/bc_desktop/submit/vdi.yml.erb
dont specify bindpath, instead allowing the cluster.d file provide the bindpath.
=> dont specify bindpath

apps.awesim.org/apps/bc_desktop/vdi.yml, ondemand.osc.edu/apps/bc_desktop/vdi.yml
disable Gnome on lightweight Cardinal desktops
=> disable Gnome on lightweight Cardinal desktops

ondemand.osc.edu/apps/dashboard/views/widgets/_classroom.html
fix classroom widget for the 4.0 upgarde.
=> fix classroom widget

apps.awesim.org/apps/bc_desktop/cardinal.yml.erb, ondemand.osc.edu/apps/bc_desktop/cardinal.yml.erb
correct Cardina's node_type help text
=> correct Cardina's node_type help text

apps.awesim.org/apps/bc_desktop/cardinal.yml.erb, ondemand.osc.edu/apps/bc_desktop/cardinal.yml.erb
add hugemem to cardinal desktop
=> add hugemem to cardinal desktop

apps.awesim.org/apps/dashboard/views/batch_connect/sessions/card/_card_header.html.erb, apps.totalsim.us/apps/dashboard/views/batch_connect/sessions/card/_card_header.html.erb, ondemand.osc.edu/apps/dashboard/views/batch_connect/sessions/card/_card_header.html.erb
=> patch OSC to fix bc card bug

class.osc.edu/apps/dashboard/views/batch_connect/sessions/_card_header.html.erb
bc card bugfix for class.osc.edu too
=> bc card bugfix for class.osc.edu too

apps.awesim.org/apps/shell/env, class.osc.edu/apps/shell/env, ondemand.osc.edu/apps/shell/env
remove owens as default ssh host
=> remove owens as default ssh host

apps.awesim.org/apps/bc_desktop/nextgen-ascend.yml.erb, ondemand.osc.edu/apps/bc_desktop/nextgen-ascend.yml.erb
=> add ascend nextgen desktop
